/*=================================================================
 *
 * TEST_FUN12
 * CPP Sample driver code for CEC2011_MATLAB that calls a shared library created
 * using MATLAB Compiler SDK.
 * Refer to the MATLAB Compiler SDK documentation for more information.
 *
 *=================================================================*/
// Include the library specific header file as generated by the 
// MATLAB Compiler
#include <iostream>
#include "CEC2011_MATLAB.h"

void MY_FUNCTION12_6Sample()
{
	mxDouble xInData[] = {100.0, 50.0, 80.0, 50.0, 50.0, 50.0};
	mwArray xIn(1, 6, mxDOUBLE_CLASS);
	xIn.SetData(xInData, 6);

	mwArray yOut;
	mwArray CountOut;
	try
	{
		MY_FUNCTION12_6(2, yOut, CountOut, xIn);
		std::cout << yOut << std::endl;
		std::cout << CountOut << std::endl;
	}
	catch (const mwException& e)
	{
		std::cerr << e.what() << std::endl;
	}
	catch (...)
	{
		std::cerr << "Unexpected error thrown" << std::endl;
	}
}

int run_main(int argc, const char **argv)
{
	if (!CEC2011_MATLABInitialize())
	{
		std::cerr << "Could not initialize the library properly" << std::endl;
		return -2;
	}
	else
	{
		MY_FUNCTION12_6Sample();
		// Call the application and library termination routine
		CEC2011_MATLABTerminate();
	}
	// Note that you should call mclTerminateApplication at the end of
	// your application to shut down all MATLAB Runtime instances.
	mclTerminateApplication();
	return 0;
}

// The main routine. On macOS, the main thread runs the system code, and
// user code must be processed by a secondary thread. On other platforms, 
// the main thread runs both the system code and the user code.
int main(int argc, const char **argv)
{
	/* Call the mclInitializeApplication routine. Make sure that the application
	 * was initialized properly by checking the return status. This initialization
	 * has to be done before calling any MATLAB APIs or MATLAB Compiler SDK
	 * generated shared library functions.
	 */
	if (!mclInitializeApplication(nullptr, 0))
	{
		std::cerr << "Could not initialize the application." << std::endl;
		return -1;
	}
	return mclRunMain(static_cast<mclMainFcnType>(run_main), argc, argv);
}
