/*=================================================================
 *
 * TEST_ANTENA
 * CPP Sample driver code for CEC2011_MATLAB that calls a shared library created
 * using MATLAB Compiler SDK.
 * Refer to the MATLAB Compiler SDK documentation for more information.
 *
 *=================================================================*/
// Include the library specific header file as generated by the 
// MATLAB Compiler
#include <iostream>
#include "CEC2011_MATLAB.h"

void antennafunccircularSample()
{
	mxDouble xInData[] = {0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.0, 0.0, 0.0};
	mwArray xIn(1, 12, mxDOUBLE_CLASS);
	xIn.SetData(xInData, 12);

	mxDouble nullInData[] = {50.0, 120.0};
	mwArray nullIn(1, 2, mxDOUBLE_CLASS);
	nullIn.SetData(nullInData, 2);

	mxDouble phi_desiredInData = 180.0;
	mwArray phi_desiredIn(phi_desiredInData);
	mxDouble distanceInData = 0.5;
	mwArray distanceIn(distanceInData);
	mwArray yOut;
	mwArray sllreturnOut;
	mwArray bwfnOut;
	try
	{
		antennafunccircular(3, yOut, sllreturnOut, bwfnOut, xIn, nullIn, phi_desiredIn, distanceIn);
		std::cout << yOut << std::endl;
		std::cout << sllreturnOut << std::endl;
		std::cout << bwfnOut << std::endl;
	}
	catch (const mwException& e)
	{
		std::cerr << e.what() << std::endl;
	}
	catch (...)
	{
		std::cerr << "Unexpected error thrown" << std::endl;
	}
}

int run_main(int argc, const char **argv)
{
	if (!CEC2011_MATLABInitialize())
	{
		std::cerr << "Could not initialize the library properly" << std::endl;
		return -2;
	}
	else
	{
		antennafunccircularSample();
		// Call the application and library termination routine
		CEC2011_MATLABTerminate();
	}
	// Note that you should call mclTerminateApplication at the end of
	// your application to shut down all MATLAB Runtime instances.
	mclTerminateApplication();
	return 0;
}

// The main routine. On macOS, the main thread runs the system code, and
// user code must be processed by a secondary thread. On other platforms, 
// the main thread runs both the system code and the user code.
int main(int argc, const char **argv)
{
	/* Call the mclInitializeApplication routine. Make sure that the application
	 * was initialized properly by checking the return status. This initialization
	 * has to be done before calling any MATLAB APIs or MATLAB Compiler SDK
	 * generated shared library functions.
	 */
	if (!mclInitializeApplication(nullptr, 0))
	{
		std::cerr << "Could not initialize the application." << std::endl;
		return -1;
	}
	return mclRunMain(static_cast<mclMainFcnType>(run_main), argc, argv);
}
