data = readmatrix('Z:/student/2018/diaoyiya/nbn_experiment/conProNBN_txt/ProName_BBOB_F01_Dim_2_SampleSize_2000000.txt', 'NumHeaderLines',1);
outputDir= '//172.24.24.151/Data/student/2018/diaoyiya/nbn_experiment/conProNBN_figure2/';
filename= 'ProName_BBOB_F01_Dim_2_SampleSize_2000000';
figureId=1;
x = linspace(0,3*pi,200);
y = cos(x) + rand(1,200);  
scatter(x,y);
sdata= size(data);
data_mat = zeros(sdata(1),2);
data_mat(:,1)= data(:,4);
data_mat(:,2)= data(:,5);
f= figure(figureId);
%f = figure('visible','off');
scatter(data_mat(:,1),data_mat(:,2),10,'filled');
filepath=[outputDir,filename,'nbn2d.png'];
exportgraphics(gcf,filepath);
clf(f);
[Mdl,tf,scores] = iforest(data_mat);
histogram(scores);
filepath=[outputDir,filename,'iforest.png'];
exportgraphics(gcf,filepath);